# Shakapacker configuration
# See: https://github.com/shakacode/shakapacker

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  shakapacker_precompile: true
  additional_paths: []
  cache_manifest: false
  webpack_loader: 'babel'
  ensure_consistent_versioning: true
  compiler_strategy: digest
  useContentHash: false
  # css_extract_ignore_order_warnings controls noisy order warnings from mini-css-extract-plugin
  css_extract_ignore_order_warnings: false

development:
  <<: *default
  compile: true
  dev_server:
    host: localhost
    port: 3035
    hmr: false
    inline_css: true
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  useContentHash: true
  cache_manifest: true
  # IMPORTANT: extract CSS files in production (MiniCssExtractPlugin)
  extract_css: true
